### ISSUE TITLE
Fetch Greeting : Toast UI issue 

### ISSUE THREAD

**Issue by KarthickSakthi** [jellydn/react-dapp#499]
By clicking the Fetch Greeting Button , Error Message in Toast Getting break out of Toast Container and onClose of Toast not working by Clicking (x) icon

Check the Attachment below!

<img width="1197" alt="Screenshot 2023-02-24 at 11 06 49 PM" src="https://user-images.githubusercontent.com/56196782/221251131-b3c4cde0-c515-4146-a012-245e49ad58f9.png">

**Comment by jellydn** [comment]
Thanks for reporting the issue. How do I reproduce this issue? @KarthickSakthi

**Comment by KarthickSakthi** [comment]
1) Go to https://dapp-demo.productsway.com
2) Just click **Fetch Greeting** Button

@jellydn

**Comment by jellydn** [comment]
Fixed by deployed new SC to Mumbai testnet.

**Comment by KarthickSakthi** [comment]
Nice
